export const GET_ALL = 'GET_ALL'
export const ADD_TO_CARD = 'ADD_TO_CARD'
export const DELETE_TO_CARD = 'DELETE_TO_CARD'
export const CHANGE_QUAN_ITEM = 'CHANGE_QUAN_ITEM'
export const TOTAL_CART = 'TOTAL_CART'