export const ASSIGNMENT_USER = "ASSIGNMENT_USER"
export const ASSIGNMENT_DETAIL = "ASSIGNMENT_DETAIL"
export const ASSIGNMENT_LIST = "ASSIGNMENT_LIST";
export const ASSIGNMENT_CREATE = "ASSIGNMENT_CREATE";
export const ASSIGNMENT_UPDATE = "ASSIGNMENT_UPDATE";
export const ASSIGNMENT_SELECTED = "ASSIGNMENT_SELECTED";
export const DELETE_ASSIGNMENT = "DELETE_ASSIGNMENT";